Repository slack-samples/bolt-js-custom-step-template, pull requests merged in 2024-08, with the labels that each got.

#38 fix: include the function_executed event to bot event subscriptions
  manifest.json
Labels: audit, bug, update

#39 chore: update project for app settings configuration first
  .env.sample
  .github/dependabot.yml
  README.md
  app.js
  package-lock.json
  package.json
  slack.json
Labels: documentation, enhancement

#41 Update Bolt version
  package-lock.json
  package.json
Labels: dependencies

#42 chore: update terminology
  README.md
  app.js
  manifest.json
  package-lock.json
  package.json
Labels: update
